"""add_render_log_to_video_assets

Revision ID: 4b8e2f980c54
Revises: 0aa3661e4fcc
Create Date: 2026-06-27 18:33:41.961182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8e2f980c54'
down_revision: Union[str, Sequence[str], None] = '0aa3661e4fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_project_events_created_at'), table_name='project_events')
    op.drop_index(op.f('idx_project_events_project_id'), table_name='project_events')
    op.drop_index(op.f('idx_script_versions_project_id'), table_name='script_versions')
    op.drop_index(op.f('idx_topics_composite_score'), table_name='topics')
    op.drop_index(op.f('idx_topics_status'), table_name='topics')
    op.drop_index(op.f('idx_topics_tags'), table_name='topics', postgresql_using='gin')
    op.add_column('video_assets', sa.Column('render_log', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_video_assets_project_id'), table_name='video_assets')
    op.drop_index(op.f('idx_projects_status'), table_name='video_projects')
    op.drop_index(op.f('idx_projects_topic_id'), table_name='video_projects')
    op.drop_index(op.f('idx_worker_tasks_project_id'), table_name='worker_tasks')
    op.drop_index(op.f('idx_worker_tasks_status'), table_name='worker_tasks')
    op.drop_index(op.f('idx_worker_tasks_type_status'), table_name='worker_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_worker_tasks_type_status'), 'worker_tasks', ['task_type', 'status'], unique=False)
    op.create_index(op.f('idx_worker_tasks_status'), 'worker_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_worker_tasks_project_id'), 'worker_tasks', ['project_id'], unique=False)
    op.create_index(op.f('idx_projects_topic_id'), 'video_projects', ['topic_id'], unique=False)
    op.create_index(op.f('idx_projects_status'), 'video_projects', ['status'], unique=False)
    op.create_index(op.f('idx_video_assets_project_id'), 'video_assets', ['project_id'], unique=False)
    op.drop_column('video_assets', 'render_log')
    op.create_index(op.f('idx_topics_tags'), 'topics', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_topics_status'), 'topics', ['status'], unique=False)
    op.create_index(op.f('idx_topics_composite_score'), 'topics', [sa.literal_column('composite_score DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_script_versions_project_id'), 'script_versions', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_events_project_id'), 'project_events', ['project_id'], unique=False)
    op.create_index(op.f('idx_project_events_created_at'), 'project_events', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
