"""add_style_config_to_projects

Revision ID: 7978c738915a
Revises: dbc24a784da8
Create Date: 2026-07-01 14:16:44.743492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7978c738915a'
down_revision: Union[str, Sequence[str], None] = 'dbc24a784da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_projects', sa.Column('style_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_projects', 'style_config')
    # ### end Alembic commands ###
