"""add_error_message_to_video_assets

Revision ID: 8fc7a573b5e9
Revises: 4b8e2f980c54
Create Date: 2026-06-27 23:18:46.447246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc7a573b5e9'
down_revision: Union[str, Sequence[str], None] = '4b8e2f980c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_assets', sa.Column('error_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_assets', 'error_message')
    # ### end Alembic commands ###
