"""add_narrative_context_to_projects

Revision ID: bb3bcd92568f
Revises: 8fc7a573b5e9
Create Date: 2026-06-30 10:36:30.296320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3bcd92568f'
down_revision: Union[str, Sequence[str], None] = '8fc7a573b5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_projects', sa.Column('narrative_context', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_projects', 'narrative_context')
    # ### end Alembic commands ###
