"""initial_schema

Revision ID: d9a1b815b39b
Revises: 
Create Date: 2026-06-24 19:51:05.654316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9a1b815b39b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('comment_tags', postgresql.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_performance_records_project_id')
    )
    op.create_table('project_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('render_engine', sa.String(length=20), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('rejection_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_counterintuitive', sa.SmallInteger(), nullable=True),
    sa.Column('score_defensibility', sa.SmallInteger(), nullable=True),
    sa.Column('score_visual', sa.SmallInteger(), nullable=True),
    sa.Column('score_freshness', sa.SmallInteger(), nullable=True),
    sa.Column('composite_score', sa.Float(), sa.Computed('(score_counterintuitive + score_defensibility + score_visual + score_freshness) / 4.0', persisted=True), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('needs_recheck', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('script_version_id', sa.UUID(), nullable=True),
    sa.Column('video_file_key', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('render_engine', sa.String(length=20), nullable=False),
    sa.Column('tts_voice', sa.String(length=50), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('current_script_version_id', sa.UUID(), nullable=True),
    sa.Column('current_video_asset_id', sa.UUID(), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('script_version_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_retries', sa.SmallInteger(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=100), nullable=True),
    sa.Column('signal_name', sa.String(length=50), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Indexes for topics
    op.create_index("idx_topics_status", "topics", ["status"])
    op.create_index("idx_topics_composite_score", "topics", ["composite_score"], postgresql_ops={"composite_score": "DESC NULLS LAST"})
    op.execute(text("CREATE INDEX IF NOT EXISTS idx_topics_tags ON topics USING GIN(tags)"))

    # Indexes for video_projects
    op.create_index("idx_projects_status", "video_projects", ["status"])
    op.create_index("idx_projects_topic_id", "video_projects", ["topic_id"])

    # Indexes for script_versions
    op.create_index("idx_script_versions_project_id", "script_versions", ["project_id"])

    # Indexes for video_assets
    op.create_index("idx_video_assets_project_id", "video_assets", ["project_id"])

    # Indexes for worker_tasks
    op.create_index("idx_worker_tasks_status", "worker_tasks", ["status"])
    op.create_index("idx_worker_tasks_project_id", "worker_tasks", ["project_id"])
    op.create_index("idx_worker_tasks_type_status", "worker_tasks", ["task_type", "status"])

    # Indexes for project_events
    op.create_index("idx_project_events_project_id", "project_events", ["project_id"])
    op.create_index("idx_project_events_created_at", "project_events", ["created_at"], postgresql_ops={"created_at": "DESC"})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_project_events_created_at", "project_events")
    op.drop_index("idx_project_events_project_id", "project_events")
    op.drop_index("idx_worker_tasks_type_status", "worker_tasks")
    op.drop_index("idx_worker_tasks_project_id", "worker_tasks")
    op.drop_index("idx_worker_tasks_status", "worker_tasks")
    op.drop_index("idx_video_assets_project_id", "video_assets")
    op.drop_index("idx_script_versions_project_id", "script_versions")
    op.drop_index("idx_projects_topic_id", "video_projects")
    op.drop_index("idx_projects_status", "video_projects")
    op.execute(text("DROP INDEX IF EXISTS idx_topics_tags"))
    op.drop_index("idx_topics_composite_score", "topics")
    op.drop_index("idx_topics_status", "topics")
    op.drop_table('worker_tasks')
    op.drop_table('video_projects')
    op.drop_table('video_assets')
    op.drop_table('topics')
    op.drop_table('script_versions')
    op.drop_table('project_events')
    op.drop_table('performance_records')
    # ### end Alembic commands ###
