"""add_prompt_components

Revision ID: dbc24a784da8
Revises: 8680bad03ccb
Create Date: 2026-07-01 14:13:16.963165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc24a784da8'
down_revision: Union[str, Sequence[str], None] = '8680bad03ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_components_category'), 'prompt_components', ['category'], unique=False)
    # ### end Alembic commands ###

    # Seed built-in components
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)

    prompt_components_table = sa.table(
        "prompt_components",
        sa.column("id", sa.String),
        sa.column("category", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("prompt_text", sa.Text),
        sa.column("is_builtin", sa.Boolean),
        sa.column("created_by", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )

    seeds = [
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000001",
            "category": "narrative_style",
            "name": "反差心理学",
            "description": "从反直觉现象切入，揭示认知偏差，适合心理学/行为经济学类内容",
            "prompt_text": "【叙事风格：反差心理学】\n整体娓娓道来，从一个反直觉的问题或现象切入，引发认知冲突，逐步揭示背后的心理机制，结尾给出可操作的认知纠偏方法。\n旁白负责讲解，每句话清晰有力，不空洞，不重复画面文字。\n语气：平静而充满反思感，像一位向朋友分享洞见的智者。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000002",
            "category": "narrative_style",
            "name": "科普解说",
            "description": "客观严谨地解释科学原理，适合物理/化学/生物/天文类内容",
            "prompt_text": "【叙事风格：科普解说】\n以准确、通俗的语言解释科学原理。从日常现象出发，逐层深入到核心机制，通过类比和图示让复杂概念变得易懂。\n旁白语气：专业而不失亲切，像一位热情的科学老师。\n避免过度简化或歪曲事实，关键数据和结论须有据可查。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000003",
            "category": "narrative_style",
            "name": "故事叙事",
            "description": "以具体人物或事件为主线，通过叙事推进知识传递",
            "prompt_text": "【叙事风格：故事叙事】\n以一个具体的人物、事件或历史片段为切入点，通过叙事推进知识传递。\n旁白语气：有画面感和代入感，像讲故事而非授课。\n在故事发展过程中自然揭示知识点，结尾点明故事的启示或意义。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000004",
            "category": "pacing",
            "name": "标准节奏（2-3分钟）",
            "description": "15-20个镜头，每镜头30-50字旁白，适合大多数知识视频",
            "prompt_text": "【叙事节奏：标准】\n目标视频时长 2-3 分钟，需要 15-20 个镜头，每个镜头旁白约 30-50 字、时长 7-10 秒。\nestimated_duration_seconds 根据旁白字数和画面复杂度估算，不得少于 5 秒。\n先用直观图形和动态关系解释概念，再在确有必要时引入关键公式；公式服务于理解，不追求数量。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000005",
            "category": "pacing",
            "name": "快节奏（1分钟）",
            "description": "8-12个镜头，每镜头20-30字旁白，适合短视频/竖屏格式",
            "prompt_text": "【叙事节奏：快节奏】\n目标视频时长约 1 分钟，需要 8-12 个镜头，每个镜头旁白约 20-30 字、时长 4-6 秒。\nestimated_duration_seconds 不得少于 3 秒。\n精简内容，只保留最核心的一个知识点，去掉所有铺垫和延伸。开头直接切入结论，结尾一句话总结。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000006",
            "category": "scene_structure",
            "name": "问题-分析-结论",
            "description": "标准知识视频三段式结构",
            "prompt_text": "【镜头结构：问题-分析-结论】\n镜头 0-1：抛出问题或反直觉现象，引发好奇\n镜头 2-4：拆解问题，建立分析框架\n镜头 5-12：逐步展开分析，以图示和实例论证\n镜头 13-15+：给出结论和实际启示",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000007",
            "category": "color_scheme",
            "name": "亮底紫色系（默认）",
            "description": "淡紫白背景 + 认知紫主色，适合心理学/思维类内容",
            "prompt_text": "【配色系统：亮底紫色系】\n背景主色（亮底）：#F7F3FF\n亮底上的文字：#1C1433；辅助注释：#8E7DC0\n核心概念色：认知紫 #6C4FD4、浅紫 #A98EE8\n语义强调：错误红 #FF6B6B、警示橙 #FFB347、理性青 #4ECDC4、结论绿 #44CF6C、直觉粉 #FF9EBB\n结构辅助：网格深底 #4A3880、网格亮底 #D4C5F0\n配色原则：红色专用于偏差/错误，绿色专用于正确/结论，不可混用。以亮底 #F7F3FF 为主场景，主色饱和度高，确保手机小尺寸下清晰可辨。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000008",
            "category": "color_scheme",
            "name": "暗底深蓝系",
            "description": "深色背景 + 科技蓝主色，适合科技/宇宙类内容",
            "prompt_text": "【配色系统：暗底深蓝系】\n背景主色（深底）：#0D1117\n深底上的文字：#E6EDF3；辅助注释：#8B949E\n核心概念色：科技蓝 #58A6FF、浅蓝 #79C0FF\n语义强调：错误红 #F85149、警示橙 #E3B341、成功绿 #3FB950、高亮青 #39D0E0\n结构辅助：网格线 #21262D\n配色原则：以深底 #0D1117 为主场景，配色模拟太空/科技感，避免过亮色块破坏沉浸感。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000009",
            "category": "animation_style",
            "name": "弹性大气感（默认）",
            "description": "弹簧动画+半透明光晕，精致细腻，适合科普和心理类视频",
            "prompt_text": "【视觉精致度规范：弹性大气感】\n构图与层次：每个镜头须有明确的视觉层次——背景装饰层 → 主体图形层 → 文字标注层，三层分离。\n图形之间保持充足间距（≥ 1.5 单位），避免拥挤感。\n半透明背景光晕：在主体元素后方放置 fill_opacity=0.12 的同色系大圆作衬底，提升视觉厚度。\n精致细节：标题镜头主标题下方配细分隔线；关键概念节点使用双圆结构（外圈半透明+内圈实心）。\n多元素用 LaggedStart 错落入场（lag_ratio=0.2），节点+连线+标注分三步出现，避免同帧全部出现。\n数字或百分比变化用 DecimalNumber 动态滚动，不要静态文字。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "a1b2c3d4-0001-4000-8000-000000000010",
            "category": "animation_style",
            "name": "简洁干净",
            "description": "最小化装饰，内容优先，适合教学和工具类视频",
            "prompt_text": "【视觉精致度规范：简洁干净】\n构图：简洁为主，每帧只保留与当前叙事直接相关的元素，不加装饰光晕或背景纹理。\n元素之间保持充足间距（≥ 1.5 单位），避免拥挤感。\n图形优先线条和基本几何形状，不追求精致光效。\n动画：入场用简单 FadeIn 或 Create，不使用弹性动画；强调用 Indicate，不用 Flash 等华丽特效。\n整体视觉服务于内容清晰传达，不为视觉精致而增加复杂度。",
            "is_builtin": True,
            "created_by": None,
            "created_at": now,
            "updated_at": now,
        },
    ]

    op.bulk_insert(prompt_components_table, seeds)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_components_category'), table_name='prompt_components')
    op.drop_table('prompt_components')
    # ### end Alembic commands ###
